package main

import (
	"context"
	"log"
	"net/http"
	"os"
	"os/signal"
	"time"

	"github.com/daniel-covelli/learn-go/product-api/handlers"
	"github.com/go-openapi/runtime/middleware"
	"github.com/gorilla/mux"
)

func main() {
	// Create a new logger. Is responsible for logging events.
	l := log.New(os.Stdout, "product-api ", log.LstdFlags)

	// Instantiate the handlers
	ph := handlers.NewProducts(l)

	// Creates a new Router instance. Router registers
	// routes to be matched and dispatches a handler.
	sm := mux.NewRouter()

	// GET route and create its subrouter.
	getRouter := sm.Methods(http.MethodGet).Subrouter()
	// Register products subroute and its associated handler.
	getRouter.HandleFunc("/products", ph.GetProducts)
	getRouter.HandleFunc("/products/{id:[0-9]+}", ph.GetProduct)

	// PUT route and create its subrouter.
	putRouter := sm.Methods(http.MethodPut).Subrouter()
	// Register a products/:id subroute and its associated handler.
	putRouter.HandleFunc("/products/{id:[0-9]+}", ph.UpdateProducts)
	putRouter.Use(ph.MiddlewareValidateProduct)

	// POST route and create its subrouter.
	postRouter := sm.Methods(http.MethodPost).Subrouter()
	// Register a products subroute and its associated handler.
	postRouter.HandleFunc("/products", ph.AddProduct)
	postRouter.Use(ph.MiddlewareValidateProduct)

	// DELETE route and create its subrouter
	deleteRouter := sm.Methods(http.MethodDelete).Subrouter()
	// Register a products subroute and its associated handler
	deleteRouter.HandleFunc("/products/{id:[0-9]+}", ph.DeleteProduct)

	// Instantiate handler to serve documentation site for swagger spec
	options := middleware.RedocOpts{SpecURL: "/swagger.yaml"}
	redocHandler := middleware.Redoc(options, nil)
	// Gets api documentation generated by Redoc
	getRouter.Handle("/docs", redocHandler)
	// Endpoint exposing swagger.yaml
	getRouter.Handle("/swagger.yaml", http.FileServer(http.Dir("./")))

	// Instantiate server at port 9090 and invoke router instance.
	s := &http.Server{
		Addr:         ":9090",
		Handler:      sm,
		IdleTimeout:  120 * time.Second,
		ReadTimeout:  1 * time.Second,
		WriteTimeout: 1 * time.Second,
	}

	// Start the server.
	go func() {
		l.Println("Starting server on port 9090")

		// Listen on port and direct inbound requests.
		err := s.ListenAndServe()
		if err != nil {
			l.Fatal(err)
		}
	}()

	// trap sigterm or interupt and gracefully shutdown the server
	sigChan := make(chan os.Signal)
	signal.Notify(sigChan, os.Interrupt)
	signal.Notify(sigChan, os.Kill)

	// block until a signal is received
	sig := <-sigChan
	l.Println("Recieved Terminate, gracefuls shutdown", sig)

	// graceful shutdown
	tc, _ := context.WithTimeout(context.Background(), 30*time.Second)
	s.Shutdown(tc)
}
